### ISSUE TITLE
Is this repo archived?

### ISSUE THREAD

**Issue by errordeveloper** [docker/docker-network#12]
As per @dave-tucker's [recent blog post](http://blog.docker.com/2015/04/docker-networking-takes-a-step-in-the-right-direction-2/), there is now [docker/libnetwork](https://github.com/docker/libnetwork), hence I suppose it should be indicated clearly that this repository really no longer active.

**Comment by vdemeester** [comment]
It should be, let's do it

**Comment by justincormack** [comment]
Archiving this.
